---
# To provision a HostEurope host, use this command:
# ... not sure

# To provision a vagrant host, use this command:
# ansible-playbook -i ansible/staging ansible/setup.yml -u vagrant -s -e "ansible_ssh_private_key_file=/home/forcer/.vagrant.d/insecure_private_key ansible_ssh_user=vagrant"

- hosts: server
  gather_facts: False
  tags: init
  vars:
  - admin_user: ansible

  tasks:
  - name: INIT | Update APT cache
    raw: apt-get -yq update
    tags: init

  - name: INIT | Install essential packages for ansible
    raw: apt-get -yq install python python-apt
    tags: init

  - name: INIT | Create administrator account
    user: name={{admin_user}}
          state=present
          system=yes
          shell=/bin/sh
    tags: init

  - name: INIT | Install ssh public key
    authorized_key: user={{admin_user}}
                    key="{{ lookup('file', ansible_ssh_public_key_file) }}"

  - name: INIT | Ensure includedir statement in sudoers
    lineinfile: dest=/etc/sudoers
                regexp="#includedir /etc/sudoers.d"
                line="#includedir /etc/sudoers.d"
                state=present

  - name: INIT | Ensure sudo permissions for {{admin_user}}
    lineinfile: |
      dest=/etc/sudoers.d/{{admin_user}}
      regexp="{{admin_user}} ALL=(ALL) NOPASSWD: ALL"
      line="{{admin_user}} ALL=(ALL) NOPASSWD: ALL"
      state=present
      create=yes
      mode=0440 owner=root group=root
