---
- name: Install package supervisor
  apt: pkg=supervisor state=present update_cache=yes
  tags: supervisor

- name: Start and enable supervisor
  service: name=supervisor state=running enabled=yes
  tags: supervisor
